### ISSUE TITLE
Not able to set TTL

### ISSUE THREAD

**Issue by mindnuts** [ssdb/nodessdb#5]
Hi trying to connect to SSDB using official driver, there is no "setx" functionality available. Also missing are "ttl" and "exists" commands for KV pairs.

M

**Comment by ideawu** [comment]
Which driver do you use, please paste link here.

**Comment by ideawu** [comment]
Hi, not all available commands are implemented in nodessdb, but you can execute any command with the method `request`.

Example:

```
request('setx', ['key', 'val', 100]);
```

**Comment by mindnuts** [comment]
@ideawu Thanks for your quick answer, btw i created a [PR](https://github.com/ssdb/nodessdb/pull/6)

**Comment by ideawu** [comment]
PR merged, thanks.
